version: '3'
services:
  app:
    image: 192.168.1.114:5001/particlecounter:latest
    ports:
      - 11111:5000
    env_file:
      - ./.env
    networks:
      - particlecounter
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  particlecounter:
