version: '3'
services:
  app:
    image: raspberrypi.local:5001/particlecounter
    ports:
      - 11111:5000
    env_file:
      - ./app.env
    networks:
      - particlecounter
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  particlecounter:
